# Window Configuration 
window:
  padding:
    x: 3
    y: 3
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #     - buttonless: Title bar, transparent background and title bar buttons
  #     - transparent: Title bar, transparent background, but no title bar buttons
  decorations: full

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

  # Scroll to the bottom when new text is written to the terminal.
  auto_scroll: false

# Font configuration
font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    family: FiraCode Nerd Font Mono
    style: Bold
  italic:
    family: FiraCode Nerd Font Mono
    style: Italic

  size: 12.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.test_test1
  glyph_offset:
    x: 0
    y: 1

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# Colors (Pink Moon)
#colors:
  # Default colors
  #primary:
    #background: '0x2a2e38'
    #foreground: '0xF0FDFF'

    # (Optional) Bright and Dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #
    # dim_foreground: '0x9a9a9a'
    # bright_foreground: '0xffffff'


  # Normal colors
  #normal:
    #black:   '0x2a2e38'
    #red:     '0xd08785'
    #green:   '0x6f98b3'
    #yellow:  '0xfdf8ce'
    #blue:    '0xa6b8cc'
    #magenta: '0xfcdbd9'
    #cyan:    '0xffd17f'
    #white:   '0xf0fdff'

  # Bright colors
  #bright:
    #black:   '0x71798a'
    #red:     '0xff3334'
    #green:   '0x9ec400'
    #yellow:  '0xe7c547'
    #blue:    '0x7aa6da'
    #magenta: '0xb77ee0'
    #cyan:    '0x54ced6'
    #white:   '0xffffff'

  # Dim colors (Optional)
  #dim:
    #black:   '0x333333'
    #red:     '0xf2777a'
    #green:   '0x99cc99'
    #yellow:  '0xffcc66'
    #blue:    '0x6699cc'
    #magenta: '0xcc99cc'
    #cyan:    '0x66cccc'
    #white:   '0xdddddd'

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '0x1e2127'
    foreground: '0xabb2bf'

  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'

  # Optional: Colors the cursor will use (test)
  cursor:
    text: '0x2a2e38'
    # cursor: '0x71798a'
    # cursor: '0xF0FDFF'
    # cursor: '0xe6d3c6'
    cursor: '0xffd17f'

  selection:
    text: '0x2a2e38'
    cursor: '0xF0FDFF'

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false
  # Faux Scrollback
  #
  # The `faux_scrollback_lines` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
  #
  # To disable this completely, set `faux_scrollback_lines` to 0.
  # faux_scrollback_lines: 1

key_bindings:
  # - { key: N,        mods: Command, command: { program: "open", args: ["-n", "/Applications/Alacritty.app"] } }
  - { key: N,        mods: Command, action: SpawnNewInstance            }
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: Paste,                   action: Paste                        }
  - { key: Copy,                    action: Copy                         }
  - { key: H,        mods: Command, action: Hide                         }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                    chars: "\x1b[H",   mode: ~AppCursor  }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                     chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: Key0,     mods: Command, action: ResetFontSize                }
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Minus,    mods: Command, action: DecreaseFontSize             }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~"                   }
